server:  port: 8888

spring:
  application:
    name: config-server  cloud:    config:      server:        git:          uri: https://gitlab.com/s4bdigital/devops/microservices-config.git          default-label: master          username: carlos.maciel@sbwebservices.net          password: XX20ks1$          clone-on-start: true          delete-untracked-branches: true          refresh-rate: 600      fail-fast: true        security:    user:      name: config      password: config